language: python
sudo: false

matrix:
  include:
  - stage: test
    arch: amd64
    python: 2.6
    dist: precise
  # - arch: arm64
  #   python: 2.7
  #   dist: bionic
  # - arch: amd64
  #   python: 2.7
  #   dist: bionic
  # - arch: ppc64le
  #   python: 2.7
  #   dist: bionic
  # - arch: amd64
  #   python: 3.2
  #   dist: precise
  # - arch: amd64
  #   python: 3.3
  #   dist: precise
  # - arch: arm64
  #   python: 3.4
  #   dist: xenial
  # - arch: amd64
  #   python: 3.4
  #   dist: xenial
  # - arch: ppc64le
  #   python: 3.4
  #   dist: xenial
  # - arch: arm64
  #   python: 3.5
  #   dist: bionic
  # - arch: amd64
  #   python: 3.5
  #   dist: bionic
  # - arch: ppc64le
  #   python: 3.5
  #   dist: bionic
  # - arch: arm64
  #   python: 3.6
  #   dist: bionic
  # - arch: amd64
  #   python: 3.6
  #   dist: bionic
  # - arch: ppc64le
  #   python: 3.6
  #   dist: bionic
  # - arch: arm64
  #   python: 3.7
  #   dist: bionic
  # - arch: amd64
  #   python: 3.7
  #   dist: bionic
  # - arch: ppc64le
  #   python: 3.7
  #   dist: bionic
  # - arch: arm64
  #   python: 3.8
  #   dist: bionic
  # - arch: amd64
  #   python: 3.8
  #   dist: bionic
  # - arch: ppc64le
  #   python: 3.8
  #   dist: bionic

  # Build and deploy the aarch64 wheels on tagged releases to master branch
  - stage: deploy
    arch: arm64
    dist: bionic
    python: 3.8
    services:
      - docker
    #if: (branch IS master) AND (tag IS present) AND (repo = python-greenlet/greenlet)
    if: (tag IS present)  #(branch = "arm64_automate_wheelbuild") AND (tag IS present)   # AND (repo = geoffreyblake/greenlet)
    install:
      - python3 -m pip install twine
    script:
      - ./make-manylinux manylinux2014_aarch64
    after_success:
      - python3 -m twine upload --skip-existing --repository-url=https://test.pypi.org/legacy wheelhouse/*

install: python setup.py build_ext -i

script: python run-tests.py
